name: Pi Deploys

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        defaults:
            run:
                working-directory: /projects
        steps:
            - name: Create test file
              run: echo "Hello world" > /projects/test.txt

            - name: Check out repository
              uses: actions/checkout@v4

            - name: Ensure destination directory exists
              run: sudo mkdir -p /usr/local/share/projects

            - name: Set permissions for directory
              run: sudo chmod -R 777 /usr/local/share/projects

            - name: Clone repository (master branch)
              run: |
                  if [ ! -d "/usr/local/share/projects/.git" ]; then
                    git clone --branch master https://github.com/vinayakshahdeo/typescript-new.git /usr/local/share/projects
                  else
                    cd /usr/local/share/projects
                    git fetch origin
                    git reset --hard origin/master
                  fi

            - name: List files (check deployment)
              run: ls -al /usr/local/share/projects
