name: Pi Deploy

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Clone repository (master branch)
              run: |
                  if [ ! -d "/home/vinayak/projects/.git" ]; then
                    git clone --branch master https://github.com/vinayakshahdeo/typescript-new.git /home/vinayak/projects
                  else
                    cd /home/vinayak/projects
                    git fetch origin
                    git reset --hard origin/master
                  fi

            - name: List files (check deployment)
              run: ls -al /home/vinayak/projects
