name: Merge and Log File Updates

on:
    push:
        branches:
            - master

jobs:
    merge-projects:
        runs-on: self-hosted
        steps:
            - name: Checkout repository into /usr/local/share/projects
              uses: actions/checkout@v4
              with:
                  path: /usr/local/share/projects
                  fetch-depth: 0

            # List updated files and save to log
            - name: Log recently written files
              run: |
                  find /usr/local/share/projects -type f -mmin -5 | sort | tee /usr/local/share/projects/updated_files.log

            # Optionally, print the log file
            - name: Show update log
              run: cat /usr/local/share/projects/updated_files.log
